import type { Metadata } from "next";
import { Rubik, Fira_Code } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import "./globals.css";
import Header from "@/components/Header/Header";
import { AppContainer } from "@/components/AppContainer";
import { ThemeProvider } from "@/components/ThemeProvider";

const rubik = Rubik({
  subsets: ["arabic", "latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-rubik",
});

const firaMono = Fira_Code({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-fira-mono",
});

export const metadata: Metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body className={`${rubik.variable} ${firaMono.variable} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider
            attribute={"class"}
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <AppContainer>{children}</AppContainer>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
